In [1]:
import pandas as pd

In [2]:
df= pd.read_csv('Concrete_Data.csv')
df.head()

Cement (component 1)(kg in a m^3 mixture)  \
0                                      540.0   
1                                      540.0   
2                                      332.5   
3                                      332.5   
4                                      198.6   

   Blast Furnace Slag (component 2)(kg in a m^3 mixture)  \
0                                                0.0       
1                                                0.0       
2                                              142.5       
3                                              142.5       
4                                              132.4       

   Fly Ash (component 3)(kg in a m^3 mixture)  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   

   Water  (component 4)(kg in a m^3 mixture)  \
0                                      162.0   
1                                      162.0   
2                                      228.0   
3                                      228.0   
4                                      192.0   

   Superplasticizer (component 5)(kg in a m^3 mixture)  \
0                                                2.5     
1                                                2.5     
2                                                0.0     
3                                                0.0     
4                                                0.0     

   Coarse Aggregate  (component 6)(kg in a m^3 mixture)  \
0                                             1040.0      
1                                             1055.0      
2                                              932.0      
3                                              932.0      
4                                              978.4      

   Fine Aggregate (component 7)(kg in a m^3 mixture)  Age (day)  \
0                                              676.0         28   
1                                              676.0         28   
2                                              594.0        270   
3                                              594.0        365   
4                                              825.5        360   

   Concrete compressive strength(MPa, megapascals)   
0                                             79.99  
1                                             61.89  
2                                             40.27  
3                                             41.05  
4                                             44.30

In [56]:
X = df.iloc[:3,:-1].values


In [57]:
print(X)

[[ 540.     0.     0.   162.     2.5 1040.   676.    28. ]
 [ 540.     0.     0.   162.     2.5 1055.   676.    28. ]
 [ 332.5  142.5    0.   228.     0.   932.   594.   270. ]]


In [12]:
type(X)

numpy.ndarray

In [13]:
X.shape

(1, 8)

In [15]:
a = X.shape

In [16]:
print(a)

(1, 8)


In [17]:
type(a)

tuple

In [18]:
rows = a[0]

In [19]:
cols = a[1]

In [20]:
print(f"Rows: {rows}, Cols: {cols}")

Rows: 1, Cols: 8


In [21]:
rows = X.shape[0]

In [22]:
cols = X.shape[1]

In [23]:
rows

1

In [24]:
cols

8

In [116]:
rows,cols = X.shape

In [117]:
print(rows,cols)

3 8


In [45]:
print(rows)

3


In [46]:
from random import shuffle

In [48]:
ind_list = [i for i in range(rows)]

In [100]:
ind_list

[2, 1, 0]

In [97]:
shuffle(ind_list)

In [98]:
X_new = X[ind_list,:]
X = X_new

In [99]:
print(X_new)

[[ 540.     0.     0.   162.     2.5 1055.   676.    28. ]
 [ 540.     0.     0.   162.     2.5 1040.   676.    28. ]
 [ 332.5  142.5    0.   228.     0.   932.   594.   270. ]]


In [96]:
print(X)

[[ 332.5  142.5    0.   228.     0.   932.   594.   270. ]
 [ 540.     0.     0.   162.     2.5 1040.   676.    28. ]
 [ 540.     0.     0.   162.     2.5 1055.   676.    28. ]]


In [3]:
import numpy as np

In [101]:
len(X[0])

8

In [111]:
s = np.random.uniform(-1,1,8)

In [112]:
s

array([-0.32090228, -0.81960933,  0.28404937,  0.91516772, -0.57590014,
        0.18370105, -0.71412269, -0.05325627])

In [110]:
X[1]

array([ 540. ,    0. ,    0. ,  162. ,    2.5, 1040. ,  676. ,   28. ])

In [120]:
X.dot(s)

array([-316.90331455, -319.65883032, -282.19478696])

In [4]:
y = np.array([])

In [5]:
y

array([], dtype=float64)

In [122]:
a = np.array([[1,3],[6,4]])

In [124]:
np.sum(a,axis = 1)

array([ 4, 10])

In [126]:
np.maximum(a,3)

array([[3, 3],
       [6, 4]])

In [127]:
b = np.array([1,2])

In [133]:
c = (a.T).dot(b)
print(c)

[13 11]


In [135]:
np.sum(c)


24

In [136]:
a[0]

array([1, 3])

In [138]:
np.dot(a,b)

array([ 7, 14])

In [139]:
ind = [1,2,3,4]

In [144]:
a = np.array([1,2,3])
b = np.array([[2,1],[3,1],[4,1]])
np.dot(a,b)


array([20,  6])

In [146]:
b.shape[1]

2

In [147]:
len(b)

3

In [8]:
help(y.argmax)

Help on built-in function argmax:

argmax(...) method of numpy.ndarray instance
    a.argmax(axis=None, out=None)
    
    Return indices of the maximum values along the given axis.
    
    Refer to `numpy.argmax` for full documentation.
    
    See Also
    --------
    numpy.argmax : equivalent function



In [1]:
import numpy as np

In [3]:
a = np.zeros((2,2))

In [4]:
b = np.zeros((2,))

In [5]:
c = (a,b)

In [6]:
c


(array([[0., 0.],
        [0., 0.]]), array([0., 0.]))

In [7]:
for data,label in c:
    print(f'datashape = {data.shape},labelshape={label.shape}')

datashape = (2,),labelshape=(2,)
datashape = (),labelshape=()
